---@diagnostic disable: undefined-global
-- InventoryApiController server to server events
AddEventHandler("vorpCore:subWeapon", InventoryAPI.subWeapon)
AddEventHandler("vorpCore:giveWeapon", InventoryAPI.giveWeapon)
AddEventHandler("vorpCore:registerWeapon", InventoryAPI.registerWeapon)
AddEventHandler("vorpCore:addItem", InventoryAPI.addItem)
AddEventHandler("vorpCore:subItem", InventoryAPI.subItem)
AddEventHandler("vorpCore:setItemMetadata", InventoryAPI.setItemMetadata)
AddEventHandler("vorpCore:subItemID", InventoryAPI.subItemID)
AddEventHandler("vorpCore:getItem", InventoryAPI.getItem)
AddEventHandler("vorpCore:getItemByMainId", InventoryAPI.getItemByMainId)
AddEventHandler("vorpCore:getItemByName", InventoryAPI.getItemByName)
AddEventHandler("vorpCore:getcomps", InventoryAPI.getcomps)
AddEventHandler("vorpCore:deletegun", InventoryAPI.deleteWeapon)
AddEventHandler("vorpinventory:removeammo", InventoryAPI.removeAllUserAmmo)
AddEventHandler("vorpCore:getItemContainingMetadata", InventoryAPI.getItemContainingMetadata)
AddEventHandler("vorpCore:getItemMatchingMetadata", InventoryAPI.getItemMatchingMetadata)
AddEventHandler("vorpCore:getItemCount", InventoryAPI.getItemCount)
AddEventHandler("vorpCore:getUserInventory", InventoryAPI.getInventory)
AddEventHandler("vorpCore:canCarryItems", InventoryAPI.canCarryAmountItem)
AddEventHandler("vorpCore:canCarryItem", InventoryAPI.canCarryItem)
AddEventHandler("vorpCore:canCarryWeapons", InventoryAPI.canCarryAmountWeapons)
AddEventHandler("vorpCore:subBullets", InventoryAPI.subBullets)
AddEventHandler("vorpCore:addBullets", InventoryAPI.addBullets)
AddEventHandler("vorpCore:getWeaponBullets", InventoryAPI.getWeaponBullets)
AddEventHandler("vorpCore:getUserWeapons", InventoryAPI.getUserWeapons)
AddEventHandler("vorpCore:getUserWeapon", InventoryAPI.getUserWeapon)
AddEventHandler("vorpCore:registerUsableItem", InventoryAPI.registerUsableItem)
AddEventHandler("vorpCore:registerInventory", InventoryAPI.registerInventory)
AddEventHandler("vorpCore:removeInventory", InventoryAPI.removeInventory)
AddEventHandler("vorpCore:openCustomInventory", InventoryAPI.openInventory)   -- main or secondary
AddEventHandler("vorpCore:closeCustomInventory", InventoryAPI.closeInventory) -- main or secondary
AddEventHandler("vorpCore:setInventoryItemLimit", InventoryAPI.setCustomInventoryItemLimit)
AddEventHandler("vorp_inventory:Server:AddPermissionMoveToCustom", InventoryAPI.AddPermissionMoveToCustom)
AddEventHandler("vorp_inventory:Server:AddPermissionTakeFromCustom", InventoryAPI.AddPermissionTakeFromCustom)
AddEventHandler("vorp_inventory:Server:BlackListCustom", InventoryAPI.BlackListCustom)
AddEventHandler("vorpCore:setInventoryWeaponLimit", InventoryAPI.setCustomInventoryWeaponLimit)
AddEventHandler("vorp_inventory:Server:updateCustomInventorySlots", InventoryAPI.updateCustomInventorySlots)
