PlayerSkin = {
    ShouldersS                           = 0.0,
    ShouldersT                           = 0.0,
    ShouldersM                           = 0.0,
    ArmsS                                = 0.0,
    LegsS                                = 0.0,
    CalvesS                              = 0.0,
    ChestS                               = 0.0,
    WaistW                               = 0.0,
    HipsS                                = 0.0,
    FaceW                                = 0.0,
    FaceD                                = 0.0,
    FaceS                                = 0.0,
    NeckW                                = 0.0,
    NeckD                                = 0.0,
    MouthCLW                             = 0.0,
    MouthCRW                             = 0.0,
    MouthCLD                             = 0.0,
    MouthCRD                             = 0.0,
    MouthCLH                             = 0.0,
    MouthCRH                             = 0.0,
    MouthCLLD                            = 0.0,
    MouthCRLD                            = 0.0,
    EyeLidL                              = 0.0,
    EyeLidR                              = 0.0,
    sex                                  = "mp_male",
    albedo                               = 0,
    HeadType                             = 0,
    BodyType                             = 0,
    LegsType                             = 0,
    Torso                                = 0,
    HeadSize                             = 0.0,
    EyeBrowH                             = 0.0,
    EyeBrowW                             = 0.0,
    EyeBrowD                             = 0.0,
    EarsH                                = 0.0,
    EarsW                                = 0.0,
    EarsD                                = 0.0,
    EarsL                                = 0.0,
    EyeLidH                              = 0.0,
    EyeLidW                              = 0.0,
    EyeD                                 = 0.0,
    EyeAng                               = 0.0,
    EyeDis                               = 0.0,
    EyeH                                 = 0.0,
    NoseW                                = 0.0,
    NoseS                                = 0.0,
    NoseH                                = 0.0,
    NoseAng                              = 0.0,
    NoseC                                = 0.0,
    NoseDis                              = 0.0,
    CheekBonesH                          = 0.0,
    CheekBonesW                          = 0.0,
    CheekBonesD                          = 0.0,
    MouthW                               = 0.0,
    MouthD                               = 0.0,
    MouthX                               = 0.0,
    MouthY                               = 0.0,
    ULiphH                               = 0.0,
    ULiphW                               = 0.0,
    ULiphD                               = 0.0,
    LLiphH                               = 0.0,
    LLiphW                               = 0.0,
    LLiphD                               = 0.0,
    JawH                                 = 0.0,
    JawW                                 = 0.0,
    JawD                                 = 0.0,
    ChinH                                = 0.0,
    ChinW                                = 0.0,
    ChinD                                = 0.0,
    Beard                                = 0,
    Hair                                 = 0,
    Body                                 = 0,
    Waist                                = 0,
    Eyes                                 = 0,
    Scale                                = 0.0,
    eyebrows_visibility                  = 0,
    eyebrows_tx_id                       = 0,
    eyebrows_opacity                     = 0.0,
    eyebrows_color                       = 0,
    scars_visibility                     = 0,
    scars_tx_id                          = 0,
    scars_opacity                        = 0,
    spots_visibility                     = 0,
    spots_tx_id                          = 0,
    spots_opacity                        = 0,
    disc_visibility                      = 0,
    disc_tx_id                           = 0,
    disc_opacity                         = 0,
    complex_visibility                   = 0,
    complex_tx_id                        = 0,
    complex_opacity                      = 0,
    acne_visibility                      = 0,
    acne_tx_id                           = 0,
    acne_opacity                         = 0,
    ageing_visibility                    = 0,
    ageing_tx_id                         = 0,
    ageing_opacity                       = 0,
    freckles_visibility                  = 0,
    freckles_tx_id                       = 0,
    freckles_opacity                     = 0,
    moles_visibility                     = 0,
    moles_tx_id                          = 0,
    moles_opacity                        = 0,
    grime_visibility                     = 0,
    grime_tx_id                          = 0,
    grime_opacity                        = 0,
    lipsticks_visibility                 = 0,
    lipsticks_tx_id                      = 0,
    lipsticks_palette_id                 = 0,
    lipsticks_palette_color_primary      = 0,
    lipsticks_palette_color_secondary    = 0,
    lipsticks_palette_color_tertiary     = 0,
    lipsticks_opacity                    = 0,
    shadows_visibility                   = 0,
    shadows_tx_id                        = 0,
    shadows_palette_id                   = 0,
    shadows_palette_color_primary        = 0,
    shadows_palette_color_secondary      = 0,
    shadows_palette_color_tertiary       = 0,
    shadows_opacity                      = 0,
    beardstabble_tx_id                   = 0,
    beardstabble_visibility              = 0,
    beardstabble_color_primary           = 0,
    beardstabble_opacity                 = 0,
    eyeliner_tx_id                       = 0,
    eyeliner_visibility                  = 0,
    eyeliner_color_primary               = 0,
    eyeliner_opacity                     = 0,
    eyeliner_palette_id                  = 0,
    blush_visibility                     = 0,
    blush_tx_id                          = 0,
    blush_palette_id                     = 0,
    blush_palette_color_primary          = 0,
    blush_opacity                        = 0,
    hair_tx_id                           = 0,
    hair_visibility                      = 0,
    hair_color_primary                   = 0,
    hair_opacity                         = 0,
    foundation_tx_id                     = 0,
    foundation_visibility                = 0,
    foundation_palette_id                = 0,
    foundation_palette_color_primary     = 0,
    foundation_palette_color_secondary   = 0,
    foundation_palette_color_tertiary    = 0,
    foundation_opacity                   = 0,
    paintedmasks_tx_id                   = 0,
    paintedmasks_visibility              = 0,
    paintedmasks_palette_id              = 0,
    paintedmasks_palette_color_primary   = 0,
    paintedmasks_palette_color_secondary = 0,
    paintedmasks_palette_color_tertiary  = 0,
    paintedmasks_opacity                 = 0,

}

PlayerClothing = {
    Poncho      = { comp = -1 },
    Glove       = { comp = -1 },
    RingRh      = { comp = -1 },
    Gauntlets   = { comp = -1 },
    Spats       = { comp = -1 },
    GunbeltAccs = { comp = -1 },
    NeckTies    = { comp = -1 },
    bow         = { comp = -1 },
    RingLh      = { comp = -1 },
    Loadouts    = { comp = -1 },
    Boots       = { comp = -1 },
    Suspender   = { comp = -1 },
    NeckWear    = { comp = -1 },
    Holster     = { comp = -1 },
    CoatClosed  = { comp = -1 },
    EyeWear     = { comp = -1 },
    Shirt       = { comp = -1 },
    Gunbelt     = { comp = -1 },
    Hat         = { comp = -1 },
    Spurs       = { comp = -1 },
    Cloak       = { comp = -1 },
    Vest        = { comp = -1 },
    Belt        = { comp = -1 },
    Pant        = { comp = -1 },
    Skirt       = { comp = -1 },
    Coat        = { comp = -1 },
    Mask        = { comp = -1 },
    Accessories = { comp = -1 },
    Buckle      = { comp = -1 },
    Bracelet    = { comp = -1 },
    Satchels    = { comp = -1 },
    Dress       = { comp = -1 },
    Badge       = { comp = -1 },
    Armor       = { comp = -1 },
    Teeth       = { comp = -1 },
    Chap        = { comp = -1 },
}