RegisterNetEvent("vorpInventory:giveItemsTable", InventoryService.processItems)
RegisterNetEvent("vorpInventory:giveInventory", InventoryService.getInventory)
RegisterNetEvent("vorpCoreClient:SetItemMetadata", InventoryApiService.SetItemMetadata)
RegisterNetEvent("vorpInventory:giveLoadout", InventoryService.getLoadout)
RegisterNetEvent("vorpInventory:receiveItem", InventoryService.receiveItem)
RegisterNetEvent("vorpInventory:removeItem", InventoryService.removeItem)
RegisterNetEvent("vorpInventory:receiveWeapon", InventoryService.receiveWeapon)
--shared
RegisterNetEvent("vorp:SelectedCharacter")
AddEventHandler("vorp:SelectedCharacter", InventoryService.onSelectedCharacter)
