Config.Language = {
    ["presstobuy"] = "Premi ~e~G~q~ Per personalizzare le armi",
    ["presstocraft"] = "Premi ~e~G~q~ Per craftare le armi",
    ["presstoshop"] = "Premi ~e~G~q~ Per comprare le armi",
    ["tooclose"] = "Qualcuno è troppo vicino",
    ["openmenu"] = "Apri",
    ["rotateitem1"] = "Premi ~e~1~q~ Per ruotare l'arma",
    ["rotateitem2"] = "Premi ~e~2~q~ Per ruotare l'arma",
    ["rotateitem3"] = "Premi ~e~3~q~ Per ruotare l'arma",
    ["rotateitem4"] = "Premi ~e~4~q~ Per ruotare l'arma",

    ["dollar"] = " $",




    ["craftingloading"] = "Fabbricando...",
    ["customloading"] = "Fabbricando l'accessorio..",
    ["pleaserequip"] = "Per favore riequipaggia l'arma dal tuo inventario",
    ["scrolltoexit"] = "Vai in fondo al menu per uscire",
    ["wrongjobcuztom"] = "Non sei un armaiolo!",
    ["wrongjobcrafting"] = "Non sei un armaiolo!",
    ["customization"] = "Personalizzazione Arma",
    ["crafting"] = "Fabbricazione",
    ["shop"] = "Armeria",
    ["buyweapons"] = "Compra Armi",
    ["buyammo"] = "Compra Munizioni",
    ["weaponcrafting"] = "Costruzione armi",
    ["ammocrafting"] = "Costruzione munizioni",
    ["areusureexit"] = "Sicuro di voler uscire ?",
    ["comps"] = "Componenti",
    ["sights"] = "Mirini",
    ["rifling"] = "Rigatura",
    ["other"] = "Canna",
    ["scopecolor"] = "Materiale Mirino",
    ["wrap"] = "Involucro",
    ["wrapcolor"] = "Colore Involucro",
    ["barrel"] = "Materiale Canna",
    ["trigger"] = "Materiale Grilletto",
    ["variant"] = "Variante arma",
    ["frame"] = "Materiale corpo",
    ["frontsight"] = "Materiale mirino frontale",
    ["cylinder"] = "Materiale meccanismo",
    ["gripbody"] = "Materiale impugnatura",
    ["grip"] = "Decalcomanie impugnatura",
    ["decal"] = "Decalcomanie arma",
    ["decalcylinder"] = "Decalcomanie meccanismo",
    ["decalframe"] = "Decalcomanie corpo",
    ["decalbarrel"] = "Decalcomanie canna",
    ["decalcolor"] = "Materiale Decalcomanie",
    ["cylinder2"] = "Materiale Decalcomanie Meccanismo",
    ["frame2"] = "Materiale Decalcomanie Corpo",
    ["barrel2"] = "Materiale Decalcomanie Canna",
    ["buyselect"] = "Compra selezione",
    ["total"] = "Totale: ",
    ["exitmenu"] = "Esci dal Menu",
    ["cost"] = "Costo: ",
    ["craft"] = "Costruisci",
    ["count"] = "Quantità: ",
    ["yes"] = "Si",
    ["no"] = "No",
    ["remove"] = "Remove",
    ["price"] = " / Prezzo: ",
    ["label"] = "Tipo: ",
    ["wrongwptype"] = "Tipo di arma sbagliato",
    ["craftingwepmods"] = "Costruendo modifiche all'arma",
    ["cantafford"] = "Non puoi permettertelo",
    ["syn_weapons"] = "Armi: ",
    ["bought"] = " Comprato ",
    ["youboughta"] = "Hai comprato un ",
    ["fors"] = " per ",
    ["nomoney"] = "Non hai abbastanza soldi",
    ["cantcarrywep"] = "Non puoi portare più armi",
    ["cantcarryitem"] = "Non puoi portare più oggetti",
    ["crafted"] = " Costruito ",
    ["nomaterial"] = "Non hai materiali sufficienti",
    ["weprec"] = "Hai ricevuto un'arma",




    ----- new lines
    ["confirm"] = "Conferma",
    ["amount"] = "Quantità",
    ["invalidamount"] = "Quantità non valida",
    ["craftcost"] = "Costo craft: ",
    ["nomoneycraft"] = "Non hai abbastanza soldi per craftare",
}
