-- * SELL ITEMS  * --

-- * TO ADD DECIMAL PRICES TO THE RANDOMPRICE DO IT LIKE THIST math.random(30, 50) / 100 >> this will equal to 0.30 to 0.50 or math.random(300, 500) / 100 will equal to 3.00 to 5.00

-- * THESE ARE JUST EXAMPLES YOU MUST CONFIGURE YOUR OWN STORES *--

Config.SellItems = {
    Valentine = {                                    -- name must be the same as  in the stores
        {
            itemLabel = "Pick Axe",                  -- Label of the item
            itemName = "pickaxe",                    -- same as in your database
            currencyType = "cash",                   -- cash or gold
            sellprice = 40,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(30, 50) / 100, -- random price between 30 and 50 if randomprices is true in this store. adding a /100 the price will be in decimals
            desc = "sell pick axe",                  -- menu description
            category = "tools",                      -- category where this item will show up if set in the store config
            itemLimit = 0,                           -- limit of this item in the store to be sold for  all players
            -- weapon = false,                    -- set to true if you want to sell weapons, or delete this from items
        },
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(1, 5),
            desc = "sell delicious hand picked apples",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Bread",
            itemName = "bread",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(1, 5),
            desc = "sell bread",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(10),
            desc = "sell water",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(25, 42),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Revolver Lemat",
            itemName = "WEAPON_REVOLVER_LEMAT",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave 0
        },
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave 0
        },


    },
    Rhodes = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Strawberry = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Blackwater = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Armadillo = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Tumbleweed = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    StDenis = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Vanhorn = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    BlackwaterFishing = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Wapiti = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 45),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(32, 52),
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
}